name: JD_Sign_Action

on:
  repository_dispatch:
  release:
    types: published
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: 0 20 * * *
  watch:
    types: started
    
env:
  JD_COOKIE: ${{ secrets.__jdu=15712395854741546845677; shshshfpb=tcRCgVMoo5lZlw90TdYLExw%3D%3D; pinId=PUdGmrnRkFYDDYPoGCGktbV9-x-f3wj7; shshshfpa=39ea5d8e-43b8-5d19-c677-12de6560d19a-1571911779; pin=jd_6bfd129d9e71e; unick=%E5%8F%AA%E6%B1%82%E7%AC%AC%E4%B8%89%E6%96%B9%E5%88%AB%E7%BF%BB%E8%BD%A6%E4%BA%86; _tp=F4CBM%2Bnuw%2FufjkOaJYfE8oXHRZ9dxAmc9Xo8zroW%2FLQ%3D; _pst=jd_6bfd129d9e71e; user-key=848637ea-e659-44db-af3f-38dd84cc8d1f; cn=0; areaId=15; ipLoc-djd=15-1255-15944-51612; TrackID=1a7xEutWxtwa0go7L65hocJTnNnwOmFmUSooabcq9JlZDFvUbaA8cZpNRUoO-YQCMIngkgF7f3H7toV-pS_dC4Euzo_M_y1t3neS2Q7sbJzsUuv1DGV32zuzYxSPaXVDE; unpl=V2_ZzNtbUsDRxJ9CRZWeRFaDGIFF1kSVkodd1wRA3hOXA0yAxEIclRCFnUUR1ZnGFQUZwQZXkVcQBxFCEdkexhdBGcHGllBUnMldDhFVEsRbAVjBRJeQF9HHHENQFF7HVkCbgYWWkRRcyVyOHZUfhxUB2MBFlheVEYSdwBFZH0aXAZmCxFfS2dCJXULRV1%2bGFUEZwEiFixWDhVxDkZXeRFYDGMGFFhCU0YSfA1CU30fbARXAA%3d%3d; __jdv=76161171|buy.jiegeng.com|t_1000159524_|tuiguang|8e5690a339784745a0893eff2f19d12d|1615278387769; PCSYCityID=CN_330000_0_0; mba_muid=15712395854741546845677; shshshfp=4db57df7a1007aa9dba5cc20e05931ba; 3AB9D23F7A4B3C9B=AOVI6WYYZU567GUO5NSTC5LKZLLU22V253XRBACUHZIC62IYQBKQUOZDRW3CGKNFVM2JFUW2HY5HSJWV5FDSIBUNIA; jcap_dvzw_fp=iI486LLkzt0hmB4rWK8YcP1L8_iwGLyArTWF2BFRHo66-uI8tm2frLp8uhRcUJVEzULUlw==; TrackerID=NPahmPr1LL7Xi2rk2L9dWRhFJv5MSS8xFxIysXRjVv3mzpwiyfx9IihXCpGcCtTgHZ7AMGZdwpxHnpmrL0Z3Qk7DoZCuFvYbay1orfc1On2v5bJzmx8snKnsWkErAt3x; pt_key=AAJgRzOYADC9gYMM6KYt1YLy0YGfAbsXe9-Ac0kUJ2Vr2F2Ycy7WIbXmG8Mcvh5xQOVAKvUyapI; pt_pin=jd_6bfd129d9e71e; pt_token=gadjfuur; pwdt_id=jd_6bfd129d9e71e; sfstoken=tk01m94651c7ca8sM3gzeDN4MjV1d3AnRimQ8AdCE9QhD8FhC9uQqTGsaHL/VNMyCeighxwBQzJ1dh43fzpmlYvuxjAO; mobilev=html5; __jda=76161171.15712395854741546845677.1571239585.1615278388.1615375834.55; __jdc=76161171; __jdb=76161171.2.15712395854741546845677|55.1615375834; mba_sid=16153758345624054744366675342.2; __jd_ref_cls=Mnpm_ComponentApplied; }}
  PUSH_KEY: ${{ secrets.SCU164290T8ee5922757cc3e3a7963dcc84b45e9e0604732c78e84e }}
  UPLOAD_BESULT_DIR: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
                
            - name: Run install
              run: npm install
              
            - name: Run Script
              run: node jd_sign.js
                
            - name: Upload result file
              uses: actions/upload-artifact@master
              if: env.UPLOAD_BESULT_DIR == 'true'
              with:
                name: result
                path: ./*.txt


