name: JD_Sign_Action

on:
  repository_dispatch:
  release:
    types: published
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: 0 20 * * *
  watch:
    types: started
    
env:
  JD_COOKIE: ${{ secrets.__jdu=15712395854741546845677; shshshfpb=tcRCgVMoo5lZlw90TdYLExw%3D%3D; pinId=PUdGmrnRkFYDDYPoGCGktbV9-x-f3wj7; shshshfpa=39ea5d8e-43b8-5d19-c677-12de6560d19a-1571911779; pin=jd_6bfd129d9e71e; unick=%E5%8F%AA%E6%B1%82%E7%AC%AC%E4%B8%89%E6%96%B9%E5%88%AB%E7%BF%BB%E8%BD%A6%E4%BA%86; _tp=F4CBM%2Bnuw%2FufjkOaJYfE8oXHRZ9dxAmc9Xo8zroW%2FLQ%3D; _pst=jd_6bfd129d9e71e; user-key=848637ea-e659-44db-af3f-38dd84cc8d1f; PCSYCityID=CN_330000_0_0; areaId=15; ipLoc-djd=15-1255-15944-51612; TrackID=1-uSlnkVxegUHzdxrOzUJ6UVpG6Ze0d0BsiCFXf72S-82-hOGz61-EDrk9iCYMyHmA8t6bHoyWLS0pEJRhCjXljSkt3WFzWZ4LGVezlPlXxUKmqB8F2flhasF0yCyi-2R; ceshi3.com=201; cn=168; unpl=V2_ZzNtbUcERxB9ARZXexBbAGIFEloRU0ZGcVtFBCxKW1AzC0INclRCFnUUR1ZnGlwUZwUZXEpcRhxFCEdkexhdBGcHGllBUnMldDhFVEsRbAVjBRJeQF9HHHENQFF7HVkCbgYWWkRRcyVyOHZUfhxUB2MBFlheVEYSdwBFZH0aXAZmCxFfS2dCJXULRV1%2bGFUEZwEiFixWDhVxDkZXeRFYDGMGFFhCU0YSfA1CU30fbARXAA%3d%3d; __jdc=76161171; __jdv=76161171|buy.jiegeng.com|t_1000159524_|tuiguang|4b5498a218644716b54b5b2afb6de9aa|1616317788417; thor=6FEED9D8C90628C0435CAF5E24840B2C2A31B4491EAC8113C2073C45D43F749D9CBAA94E1208C066B6D8EE1A1EF7EC0707259D71FC4D2A0D6B8112466A6D75F4B949E7E5AF8C75B6771B4E53072D3474AF98E969D5EEF198C81ACAF19A14E8953C81C12CA16329C6CBE91765F5B78569D2119658B48E9F48DFA7F75EE978011E6AF537F12C91F933A1C82BB6E323C02588E32D65687399A7C0D6FA577ABA5F2B; wxa_level=1; retina=0; jxsid=16163182141217480002; webp=1; mba_muid=15712395854741546845677; visitkey=251953301238678; 3AB9D23F7A4B3C9B=JHHCWGM276XW6KMAMCQ4H3OW75HCWXMLHOAOHNRRPUQAF5Q4HQ6MECNHYEXTMXS7ZDBAEG3RMDH7EWOIQPSKZIJKS4; TrackerID=wunEHSokTZ_o5pdsxzw2kMw2PnSA31U3VP1BQXdnYYiVnADR1xPS6fz5OgE5ceVgsKz_1CeJ7BvfHyx3-oJrHiLGwwmBgiKzKKY219QAXojOKt_kkgNQ8F6BLsvpN2YY; pt_key=AAJgVw8hADBpsisAy_3VUa7PXWqb2iNRpUmLLvPlywXfj87slBgZh6f6kMQHl96Gzp78lJ4ZQlI; pt_pin=jd_6bfd129d9e71e; pt_token=3ndlshb5; pwdt_id=jd_6bfd129d9e71e; sfstoken=tk01m8a311a7ba8sMngzRGYyS0FB4DKcnIelnb5RbWb4mS4N1lq/1TqBHE3H/4/sXwqA+S1zEa4R4mrLFAON04Zj6/Jg; PPRD_P=UUID.15712395854741546845677; sc_width=2560; shshshfp=e9998a7610bdef3e3465 }}
  PUSH_KEY: ${{ secrets.SCU164290T8ee5922757cc3e3a7963dcc84b45e9e0604732c78e84e }}
  UPLOAD_BESULT_DIR: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
                
            - name: Run install
              run: npm install
              
            - name: Run Script
              run: node jd_sign.js
                
            - name: Upload result file
              uses: actions/upload-artifact@master
              if: env.UPLOAD_BESULT_DIR == 'true'
              with:
                name: result
                path: ./*.txt


